---
- name: remove users
  user:
    name: "{{ item.user }}"
    state: absent
    remove: yes
  with_items:
    "{{ new_users }}"

- name: remove groups
  group:
    name: "{{ item }}"
    state: absent
  with_items:
    "{{ new_groups }}"
