---
- name: add groups
  group:
    name: "{{ item }}"
    state: present
    system: yes
  with_items:
    "{{ new_groups }}"
            
- name: add users
  user:
    name: "{{ item.user }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    append: yes
    system: yes
    password: "{{ item.password }}"
    expires: "{{ item.account_expires | default(null) }}"
    update_password: on_create
  with_items:
    "{{ new_users }}"

- name: password expires
  shell: chage -m 0 -M {{ item.password_expires }} -W 7 -I 3 {{ item.user }}
  with_items:
    "{{ new_users }}"
  ignore_errors: true
