---
- name: remove users
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  with_items:
    - "{{ dce_user }}"

- name: remove groups
  group:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ dce_group }}"
            
