---
- name: update sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "{{ item }}"
    state: absent
    owner: root
    group: root
    mode: 0600
    backup: yes
  with_items:
    - "UseDNS no"
    - "Banner /etc/issue"

