---
- name: crashkernel=256M
  lineinfile:
    path: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="crashkernel=256M"'

- name: update grub.cfg
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: install kdump
  yum: 
    name: kexec-tools
    state: present
    update_cache: yes

- name: systemd daemon-reload
  systemd:
    daemon-reload: yes

- name: sync conf
  template:
    src: kdump.conf.j2
    dest: /etc/kdump.conf
    owner: root
    group: root
    mode: 0644
  notify: restart kdump
