---
- name: stop kdump daemon
  service:
    name: kdump
    enabled: no
    state: stopped
  ignore_errors: true

- name: uninstall kdump
  yum: 
    name: kdump
    state: absent

- name: clear kdump file left
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/kdump.conf

- name: crashkernel=256M
  lineinfile:
    path: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX_DEFAULT="crashkernel=256M"'
    state: absent

- name: update grub.cfg
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg
