---
- name: sync issue & issue.net & motd
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'issue.default', dest: '/etc/issue' }
    - { src: 'issue.net.default', dest: '/etc/issue.net' }
    - { src: 'motd.default', dest: '/etc/motd' }
