---
- sysctl:
    name: vm.swappiness
    value: 5
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: fs.aio-max-nr
    value: 1048576
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: fs.file-max
    value: 6815744
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: kernel.shmall
    value: 2097152
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: kernel.shmmax
    value: 4294967295
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: kernel.shmmni
    value: 4096
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: kernel.sem
    value: 250 32000 100 128
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: net.ipv4.ip_local_port_range
    value: 9000 65500
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: net.core.rmem_default
    value: 262144
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: net.core.rmem_max
    value: 4194304
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: net.core.wmem_default
    value: 262144
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: net.core.wmem_max
    value: 1048576
    sysctl_set: yes
    state: present
    reload: yes
