---
- name: MemTotal(KB)
  shell: grep 'MemTotal:' /proc/meminfo|awk '{print $2}'
  register: result
- set_fact: 
    CONNTRACK_MAX={{ (result.stdout | float) * 1024 / 16384 / 2 }}
    CONNTRACK_BUCKETS={{ (result.stdout| float) * 1024 / 16384 / 2 / 8 }}

- sysctl:
    name: "{{ item.name }}"
    state: absent
  with_items:
    - vm.swappiness
    - fs.file-max
    - fs.aio-max-nr
    - kernel.shmall
    - kernel.shmmax
    - kernel.shmmni
    - kernel.sem
    - kernel.sysrq
    - kernel.core_uses_pid
    - kernel.msgmnb
    - kernel.msgmax
    - kernel.pid_max
    - net.core.rmem_default
    - net.core.rmem_max
    - net.core.wmem_default
    - net.core.wmem_max
    - net.core.netdev_max_backlog
    - net.core.optmem_max
    - net.ipv4.ip_local_port_range
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.default.rp_filter
    - net.ipv4.conf.default.accept_source_route
    - net.ipv4.tcp_syncookies
    - net.ipv4.tcp_max_tw_buckets
    - net.ipv4.tcp_window_scaling
    - net.ipv4.tcp_timestamps
    - net.ipv4.tcp_sack
    - net.ipv4.tcp_rmem
    - net.ipv4.tcp_wmem
    - net.ipv4.tcp_mem
    - net.ipv4.tcp_max_orphans
    - net.ipv4.tcp_max_syn_backlog
    - net.ipv4.tcp_synack_retries
    - net.ipv4.tcp_syn_retries
    - net.ipv4.tcp_tw_recycle
    - net.ipv4.tcp_tw_reuse
    - net.ipv4.tcp_fin_timeout
    - net.ipv4.tcp_keepalive_time
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.netfilter.nf_conntrack_tcp_timeout_established
    - net.netfilter.nf_conntrack_max

- name: disable modules load onboot
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/modules-load.d/netfilter.conf
    - /etc/modprobe.d/netfilter_parameter.conf

- name: unload modules
  modprobe:
    name: "{{ item }}"
    state: absent
  with_items:
    - nf_conntrack
    - nf_conntrack_ipv4
    - br_netfilter
  ignore_errors: true

