---
- name: Insert pam_cracklib.so
  pamd:
    name: "{{ item }}"
    type: password
    control: requisite
    module_path: pam_pwquality.so
    new_type: password
    new_control: requisite
    new_module_path: pam_cracklib.so
    state: before
  with_items:
    - system-auth
    - password-auth

- name: Replace all module arguments in an existing rule(pam_cracklib.so)
  pamd:
    name: "{{ item }}"
    type: auth
    control: required
    module_path: pam_faillock.so
    module_arguments: 'try_first_pass 
        retry=3 
        type= 
        ucredit=-1 
        lcredit=-1 
        ocredit=-1 
        dcredit=-1 
        minlen=8'
    state: updated
  with_items:
    - system-auth
    - password-auth

- name: Insert pam_faillock.so
  pamd:
    name: "{{ item }}"
    type: auth
    control: required
    module_path: pam_env.so
    new_type: auth
    new_control: required
    new_module_path: pam_faillock.so
    state: before
  with_items:
    - system-auth
    - password-auth

- name: Replace all module arguments in an existing rule(pam_faillock.so)
  pamd:
    name: "{{ item }}"
    type: auth
    control: required
    module_path: pam_faillock.so
    module_arguments: 'preauth
        silent
        deny=3
        unlock_time=604800
        fail_interval=900'
    state: updated
  with_items:
    - system-auth
    - password-auth

- name: Insert pam_wheel.so
  pamd:
    name: su
    type: auth
    control: sufficient
    module_path: pam_rootok.so
    new_type: auth
    new_control: required
    new_module_path: pam_wheel.so
    state: after

- name: Replace all module arguments in an existing rule(pam_wheel.so)
  pamd:
    name: su
    type: auth
    control: required
    module_path: pam_wheel.so
    module_arguments: 'use_uid'
    state: updated
