---
- name: clear pam
  pamd:
    name: "{{ item.name }}"
    type: "{{ item.type }}"
    control: "{{ item.control }}"
    module_path: "{{ item.module_path }}"
    state: "{{ item.state }}"
  with_items:
    - { 'name': system-auth, 'type': password, 'control': requisite , 'module_path': pam_cracklib.so, 'state': absent}
    - { 'name': system-auth, 'type': auth, 'control': required , 'module_path': pam_faillock.so, 'state': absent}
    - { 'name': system-auth, 'type': auth, 'control': required , 'module_path': pam_tally2.so, 'state': absent}
    - { 'name': password-auth, 'type': password, 'control': requisite , 'module_path': pam_cracklib.so, 'state': absent}
    - { 'name': password-auth, 'type': auth, 'control': required , 'module_path': pam_faillock.so, 'state': absent}
    - { 'name': password-auth, 'type': auth, 'control': required , 'module_path': pam_tally2.so, 'state': absent}
    - { 'name': su, 'type': auth, 'control': sufficient, 'module_path': pam_wheel.so, 'state': absent}
