---
- pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items:
    - { 'domain': root, 'limit_type': -, 'limit_item': nofile, 'value': 655360 }
    - { 'domain': root, 'limit_type': -, 'limit_item': nproc, 'value': 163840 }
    - { 'domain': root, 'limit_type': -, 'limit_item': stack, 'value': 10240 }
    - { 'domain': root, 'limit_type': -, 'limit_item': memlock, 'value': unlimited }
    - { 'domain': '*', 'limit_type': -, 'limit_item': nofile, 'value': 655360 }
    - { 'domain': '*', 'limit_type': -, 'limit_item': nproc, 'value': 163840 }
    - { 'domain': '*', 'limit_type': -, 'limit_item': stack, 'value': 10240 }
    - { 'domain': '*', 'limit_type': -, 'limit_item': memlock, 'value': unlimited }
