---
- name: clear pam_limits
  lineinfile:
    path: /etc/security/limits.conf
    regexp: '^{{ item.domain }}\s+{{ item.limit_type }}\s+{{ item.limit_item }}\s+{{ item.value }}$'
    state: absent
    owner: root
    group: root
    mode: 0644
  with_items:
    - { 'domain': root, 'limit_type': -, 'limit_item': nofile, 'value': 655360 }
    - { 'domain': root, 'limit_type': -, 'limit_item': nproc, 'value': 163840 }
    - { 'domain': root, 'limit_type': -, 'limit_item': stack, 'value': 10240 }
    - { 'domain': root, 'limit_type': -, 'limit_item': memlock, 'value': unlimited }
    - { 'domain': '\*', 'limit_type': -, 'limit_item': nofile, 'value': 655360 }
    - { 'domain': '\*', 'limit_type': -, 'limit_item': nproc, 'value': 163840 }
    - { 'domain': '\*', 'limit_type': -, 'limit_item': stack, 'value': 10240 }
    - { 'domain': '\*', 'limit_type': -, 'limit_item': memlock, 'value': unlimited }
